return {
    Id = "Combat",
    Label = "Combat",
    Icon = "target",
    Bookmarked = false,
    RuntimeModule = "runtime/Combat.lua",
    Sections = {
        {
            Title = "Ataques",
            Icon = "fire",
            Controls = {
                {
                    Kind = "Toggle",
                    Setting = "NoCooldown",
                    Id = "combat_no_cooldown",
                    Label = "Sem recarga",
                    Description = "Remove esperas locais de golpes e ferramentas. Recargas validadas pelo servidor podem continuar ativas.",
                    Default = false,
                },
            },
        },
        {
            Title = "Hitbox",
            Icon = "target",
            Controls = {
                {
                    Kind = "Toggle",
                    Setting = "HitboxEnabled",
                    Id = "combat_hitbox_enabled",
                    Label = "Hitbox Expander",
                    Description = "Amplia localmente a hitbox dos outros jogadores sem alterar sua posição.",
                    Default = false,
                },
                {
                    Kind = "Slider",
                    Setting = "HitboxRange",
                    Id = "combat_hitbox_range",
                    Label = "Alcance da hitbox",
                    Description = "Raio em studs. A caixa usa o dobro deste valor em cada eixo.",
                    Min = 5,
                    Max = 500,
                    Default = 15,
                    Step = 1,
                },
                {
                    Kind = "Toggle",
                    Setting = "HitboxVisible",
                    Id = "combat_hitbox_visible",
                    Label = "Mostrar área da hitbox",
                    Description = "Exibe a caixa com a mesma cor de time usada pelo ESP.",
                    Default = true,
                },
                {
                    Kind = "Slider",
                    Setting = "HitboxTransparency",
                    Id = "combat_hitbox_transparency",
                    Label = "Transparência da hitbox",
                    Min = 20,
                    Max = 95,
                    Default = 78,
                    Step = 1,
                },
            },
        },
    },
}
