return {
    Id = "Visuals",
    Label = "Visuals",
    Icon = "eye",
    Bookmarked = false,
    RuntimeModule = "runtime/Visuals.lua",
    Sections = {
        {
            Title = "Jogadores",
            Icon = "users",
            Controls = {
                {
                    Kind = "Toggle",
                    Setting = "PlayerESP",
                    Id = "visuals_player_esp",
                    Label = "ESP de jogadores",
                    Description = "Mostra nome, vida e tags confirmadas abaixo de cada jogador.",
                    Default = false,
                },
                {
                    Kind = "Toggle",
                    Setting = "PlayerESPHealth",
                    Id = "visuals_player_health",
                    Label = "Vida dos jogadores",
                    Description = "Exibe vida atual, vida máxima, porcentagem e estado de morte.",
                    Default = true,
                },
                {
                    Kind = "Toggle",
                    Setting = "PlayerESPTeams",
                    Id = "visuals_player_teams",
                    Label = "Tags de time",
                    Description = "Usa a cor do Team ou do atributo HideNSeek_Team.",
                    Default = true,
                },
                {
                    Kind = "Toggle",
                    Setting = "PlayerESPAura",
                    Id = "visuals_player_aura",
                    Label = "Aura dos jogadores",
                    Description = "Destaca o personagem através das paredes usando a cor do time.",
                    Default = true,
                },
                {
                    Kind = "Slider",
                    Setting = "PlayerESPAuraIntensity",
                    Id = "visuals_player_aura_intensity",
                    Label = "Intensidade da aura",
                    Min = 10,
                    Max = 100,
                    Default = 45,
                    Step = 5,
                },
                {
                    Kind = "Toggle",
                    Setting = "PlayerESPGlassMaker",
                    Id = "visuals_player_glassmaker",
                    Label = "Tag de Glass Maker",
                    Description = "Exibe uma tag dourada para quem possui GlassMaker=true.",
                    Default = true,
                },
                {
                    Kind = "Toggle",
                    Setting = "PlayerESPBaby",
                    Id = "visuals_player_baby",
                    Label = "Tag de portador do bebê",
                    Description = "Exibe uma tag rosa para quem possui HasBaby=true ou BabyBack.",
                    Default = true,
                },
            },
        },
        {
            Title = "Ponte de Vidro",
            Icon = "eye",
            Controls = {
                {
                    Kind = "Paragraph",
                    Label = "Glass Vision",
                    Description = "Verde = vidro real/seguro | Vermelho = vidro falso/quebrável.",
                },
                {
                    Kind = "Toggle",
                    Setting = "GlassESP",
                    Id = "visuals_glass_esp",
                    Label = "Ver vidros reais e falsos",
                    Description = "Usa profundidade normal para não cobrir os jogadores próximos.",
                    Default = false,
                },
                {
                    Kind = "Slider",
                    Setting = "GlassTransparency",
                    Id = "visuals_glass_transparency",
                    Label = "Transparência do destaque",
                    Min = 55,
                    Max = 95,
                    Default = 82,
                    Step = 1,
                },
            },
        },
    },
}
